apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
  name: sidecar-codelab
  labels:
    cloud.googleapis.com/location: "us-central1"
spec:
  template:
    spec:
      containers:
        - image: "us-central1-docker.pkg.dev/cloudrun-413119/sidecar-codelab/ingress:latest"
          ports:
            - containerPort: 8080
        - image: "us-central1-docker.pkg.dev/cloudrun-413119/sidecar-codelab/sidecar:latest"
          env:
            - name: PORT
              value: "5000"
